### ISSUE TITLE
Cannot checkout repo on windows due to invalid paths

### ISSUE THREAD

**Issue by h-vetinari** [regro/cf-graph-countyfair#33]
Due to the size of the repo, I tried a shallow clone with `--depth=1000`, but it always kept failing.

A full clone (and 20min) later, the error persists, and it's because there's stuff checked in that doesn't work on windows:
https://github.com/regro/cf-graph-countyfair/blob/master/node_attrs/conda-forge%3A%3Agit.json
https://github.com/regro/cf-graph-countyfair/blob/master/versions/conda-forge%3A%3Agit.json

```
C:\Users\[...]\Dev\conda-forge>git clone https://github.com/regro/cf-graph-countyfair
Cloning into 'cf-graph-countyfair'...
remote: Enumerating objects: 2806, done.
remote: Counting objects: 100% (2806/2806), done.
remote: Compressing objects: 100% (1993/1993), done.
remote: Total 2426497 (delta 2554), reused 985 (delta 807), pack-reused 2423691
Receiving objects: 100% (2426497/2426497), 6.87 GiB | 30.06 MiB/s, done.
Resolving deltas: 100% (2363586/2363586), done.
error: invalid path 'node_attrs/conda-forge::git.json'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'


C:\Users\[...]\Dev\conda-forge>cd cf-graph-countyfair

C:\Users\[...]\Dev\conda-forge\cf-graph-countyfair>git restore --source=HEAD :/
error: invalid path 'node_attrs/conda-forge::git.json'
error: invalid path 'versions/conda-forge::git.json'
[...hangs...]
```

I don't have a linux machine handy right now, so I cannot even submit a PR to remove those files.

CC @beckermr

**Comment by beckermr** [comment]
You can make the change in the UI which is easier for this repo anyways.

**Comment by h-vetinari** [comment]
Ha, TIL! I never used the GH UI to edit files, but that's a great idea, thanks: https://github.com/regro/cf-graph-countyfair/pull/34. Closing this (though the paths with `::` still look like an artefact to me... 🤷 )

**Comment by beckermr** [comment]
Yeah that does look weird for sure.
